"""autogenerated by genmsg_py from SpeedRequestRequest.msg. Do not edit."""
import roslib.message
import struct


class SpeedRequestRequest(roslib.message.Message):
  _md5sum = "c149f5889512e5eb2c8abd2fbf76316e"
  _type = "robucar_simulation/SpeedRequestRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 linear_speed
float64 angular_speed

"""
  __slots__ = ['linear_speed','angular_speed']
  _slot_types = ['float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       linear_speed,angular_speed
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SpeedRequestRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.linear_speed is None:
        self.linear_speed = 0.
      if self.angular_speed is None:
        self.angular_speed = 0.
    else:
      self.linear_speed = 0.
      self.angular_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2d.pack(_x.linear_speed, _x.angular_speed))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.linear_speed, _x.angular_speed,) = _struct_2d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2d.pack(_x.linear_speed, _x.angular_speed))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.linear_speed, _x.angular_speed,) = _struct_2d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2d = struct.Struct("<2d")
"""autogenerated by genmsg_py from SpeedRequestResponse.msg. Do not edit."""
import roslib.message
import struct


class SpeedRequestResponse(roslib.message.Message):
  _md5sum = "ba6f422b58183e641c592940e54dddce"
  _type = "robucar_simulation/SpeedRequestResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool speed_set
float64 linear_speed
float64 angular_speed


"""
  __slots__ = ['speed_set','linear_speed','angular_speed']
  _slot_types = ['bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       speed_set,linear_speed,angular_speed
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SpeedRequestResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.speed_set is None:
        self.speed_set = False
      if self.linear_speed is None:
        self.linear_speed = 0.
      if self.angular_speed is None:
        self.angular_speed = 0.
    else:
      self.speed_set = False
      self.linear_speed = 0.
      self.angular_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_B2d.pack(_x.speed_set, _x.linear_speed, _x.angular_speed))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.speed_set, _x.linear_speed, _x.angular_speed,) = _struct_B2d.unpack(str[start:end])
      self.speed_set = bool(self.speed_set)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_B2d.pack(_x.speed_set, _x.linear_speed, _x.angular_speed))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.speed_set, _x.linear_speed, _x.angular_speed,) = _struct_B2d.unpack(str[start:end])
      self.speed_set = bool(self.speed_set)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_B2d = struct.Struct("<B2d")
class SpeedRequest(roslib.message.ServiceDefinition):
  _type          = 'robucar_simulation/SpeedRequest'
  _md5sum = '6ae8d061002822fae34a9844454f86c5'
  _request_class  = SpeedRequestRequest
  _response_class = SpeedRequestResponse
