/* Auto-generated by genmsg_cpp for file /home/carlos/fuerte_workspace/sandbox/rosbucar/msg/CarLikeCmd.msg */
#ifndef ROSBUCAR_MESSAGE_CARLIKECMD_H
#define ROSBUCAR_MESSAGE_CARLIKECMD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rosbucar
{
template <class ContainerAllocator>
struct CarLikeCmd_ {
  typedef CarLikeCmd_<ContainerAllocator> Type;

  CarLikeCmd_()
  : action(0)
  , target_speed(0.0)
  , target_steering(0.0)
  {
  }

  CarLikeCmd_(const ContainerAllocator& _alloc)
  : action(0)
  , target_speed(0.0)
  , target_steering(0.0)
  {
  }

  typedef uint8_t _action_type;
  uint8_t action;

  typedef float _target_speed_type;
  float target_speed;

  typedef float _target_steering_type;
  float target_steering;


  typedef boost::shared_ptr< ::rosbucar::CarLikeCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosbucar::CarLikeCmd_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CarLikeCmd
typedef  ::rosbucar::CarLikeCmd_<std::allocator<void> > CarLikeCmd;

typedef boost::shared_ptr< ::rosbucar::CarLikeCmd> CarLikeCmdPtr;
typedef boost::shared_ptr< ::rosbucar::CarLikeCmd const> CarLikeCmdConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rosbucar::CarLikeCmd_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rosbucar::CarLikeCmd_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rosbucar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rosbucar::CarLikeCmd_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rosbucar::CarLikeCmd_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rosbucar::CarLikeCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "273058188caa05af1326783afad3d2f9";
  }

  static const char* value(const  ::rosbucar::CarLikeCmd_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x273058188caa05afULL;
  static const uint64_t static_value2 = 0x1326783afad3d2f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosbucar::CarLikeCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rosbucar/CarLikeCmd";
  }

  static const char* value(const  ::rosbucar::CarLikeCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rosbucar::CarLikeCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 action\n\
float32 target_speed\n\
float32 target_steering\n\
";
  }

  static const char* value(const  ::rosbucar::CarLikeCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rosbucar::CarLikeCmd_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rosbucar::CarLikeCmd_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action);
    stream.next(m.target_speed);
    stream.next(m.target_steering);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CarLikeCmd_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosbucar::CarLikeCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rosbucar::CarLikeCmd_<ContainerAllocator> & v) 
  {
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "target_speed: ";
    Printer<float>::stream(s, indent + "  ", v.target_speed);
    s << indent << "target_steering: ";
    Printer<float>::stream(s, indent + "  ", v.target_steering);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROSBUCAR_MESSAGE_CARLIKECMD_H

