<?xml version="1.0"?>

<robot xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" 
       name="Robucar">

  <xacro:macro name="head">

    <!-- Head just to know the direction the robot is facing. -->
    <link name="head">

      <inertial>
        <mass value="0.1" />
        <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" />
      </inertial>

      <visual>
        <geometry>
          <box size="0.2 0.2 0.2"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="red">
          <color rgba="0.8 0 0 1"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <box size="0.2 0.2 0.2"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>

    </link>

    <gazebo reference="head">
      <material>Gazebo/Red</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="base_to_head" type="fixed">
      <parent link="base_link"/>
      <child link="head"/>
      <origin xyz="${robot_lenght/2} 0 0"/>
    </joint>

  </xacro:macro>

</robot>
