"""autogenerated by genmsg_py from CarLikeCmd.msg. Do not edit."""
import roslib.message
import struct


class CarLikeCmd(roslib.message.Message):
  _md5sum = "273058188caa05af1326783afad3d2f9"
  _type = "robucar_gazebo_plugins/CarLikeCmd"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 action
float32 target_speed
float32 target_steering
"""
  __slots__ = ['action','target_speed','target_steering']
  _slot_types = ['uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       action,target_speed,target_steering
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(CarLikeCmd, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.action is None:
        self.action = 0
      if self.target_speed is None:
        self.target_speed = 0.
      if self.target_steering is None:
        self.target_steering = 0.
    else:
      self.action = 0
      self.target_speed = 0.
      self.target_steering = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_B2f.pack(_x.action, _x.target_speed, _x.target_steering))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.action, _x.target_speed, _x.target_steering,) = _struct_B2f.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_B2f.pack(_x.action, _x.target_speed, _x.target_steering))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.action, _x.target_speed, _x.target_steering,) = _struct_B2f.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_B2f = struct.Struct("<B2f")
