(cl:in-package gps_novatel-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOL_STATUS-VAL
          SOL_STATUS
          POS_TYPE-VAL
          POS_TYPE
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          ONDULATION-VAL
          ONDULATION
          DATUM_ID-VAL
          DATUM_ID
          SIGMALAT-VAL
          SIGMALAT
          SIGMALON-VAL
          SIGMALON
          SIGMAALT-VAL
          SIGMAALT
          BASE_ID-VAL
          BASE_ID
          DIFF_AGE-VAL
          DIFF_AGE
          SOL_AGE-VAL
          SOL_AGE
          NOBS-VAL
          NOBS
          NGPSL-VAL
          NGPSL
          NL1-VAL
          NL1
          NL2-VAL
          NL2
))